name: CI - Unit Test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./.net/ExploringActions/ExploringActions.sln

      - name: Build the solution
        run: dotnet build ./.net/ExploringActions/ExploringActions.sln --configuration Release --no-restore

      - name: Run unit tests with report
        run: dotnet test ./.net/ExploringActions/TestProjectExploringActions/TestProjectExploringActions.csproj --configuration Release --no-build --logger "trx;LogFileName=TestResults.trx"
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ./.net/ExploringActions/TestProjectExploringActions/TestResults/TestResults.trx
